language: node_js
sudo: false
dist: trusty

node_js:
  - "9.0"
  - "8.9"
  - "8.8"
  - "8.7"
  - "8.6"
  - "8.5"
  - "8.4"
  - "8.3"
  - "8.2"
  - "8.1"
  - "8.0"
  - "7.10"
  - "7.9"
  - "7.8"
  - "7.7"
  - "7.6"
  - "7.5"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - 6
  - 5
  - 4
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

os: linux

script: "npm test"

